services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    user: 1000:1000
    image: yt-dlp-application
    container_name: yt-dlp-application
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    networks:
      - laravel_app
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_app
networks:
  laravel_app:
    driver: bridge